package vn.local.queryrouter.core

object LocalKnowledge {
    val fields: List<String> = listOf(
        "Định danh & giấy tờ", "Dịch vụ công", "Thuế & doanh nghiệp", "BHXH & BHYT", "Y tế",
        "Giao thông", "Điện", "Nước", "Viễn thông & Internet", "Ngân hàng & thanh toán",
        "Giáo dục", "Việc làm & lao động", "Nhà đất & xây dựng", "Tư pháp & hộ tịch", "An sinh xã hội",
        "Công dân số địa phương", "Công việc Đảng", "Môi trường & đô thị", "Văn hóa & cộng đồng", "Khác"
    )

    val sources: List<SourceRef> = listOf(
        SourceRef("src_bhyt_initial_local", "Danh sách cơ sở KCB BHYT ban đầu", "Cơ quan BHXH có thẩm quyền", "Chưa nạp văn bản chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_tax_status_local", "Danh mục trạng thái mã số thuế", "Cơ quan thuế có thẩm quyền", "Chưa nạp văn bản chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_public_procedure_local", "Danh mục thủ tục hành chính", "Cơ quan Nhà nước có thẩm quyền", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_health_facility_local", "Danh mục cơ sở y tế và chuyên khoa", "Cơ quan y tế có thẩm quyền", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_utility_provider_local", "Danh mục đơn vị cung cấp dịch vụ thiết yếu", "Đơn vị/cơ quan công bố chính thức", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_transport_local", "Danh mục dịch vụ và thủ tục giao thông", "Cơ quan giao thông có thẩm quyền", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_education_local", "Danh mục giáo dục và tuyển sinh", "Cơ quan giáo dục có thẩm quyền", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_labor_local", "Danh mục lao động, việc làm và an sinh", "Cơ quan có thẩm quyền", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_land_local", "Danh mục đất đai, xây dựng và quy hoạch", "Cơ quan có thẩm quyền", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN),
        SourceRef("src_civil_local", "Danh mục tư pháp và hộ tịch", "Cơ quan có thẩm quyền", "Chưa nạp gói dữ liệu chính thức", status = DataStatus.UNKNOWN)
    )

    val records: List<KnowledgeRecord> = listOf(
        KnowledgeRecord("kr_tax_03", "Thuế & doanh nghiệp", "Trạng thái mã số thuế 03", "meaning", "Chỉ được trả lời chi tiết sau khi gói dữ liệu chính thức đã được nạp và còn hiệu lực.", listOf("trạng thái 03", "mã số thuế 03"), "src_tax_status_local", DataStatus.UNKNOWN)
    )

    val apps: List<AppProfile> = listOf(
        AppProfile("vneid", "VNeID", "Định danh & giấy tờ", "Định danh điện tử và giấy tờ số theo chức năng chính thức.", "com.vnid", listOf("open_vneid")),
        AppProfile("vnetraffic", "VNeTraffic", "Giao thông", "Tra cứu và xử lý nhu cầu giao thông theo đường gọi đã xác minh.", null, listOf("traffic_fine", "vehicle_lookup")),
        AppProfile("vssid", "VssID", "BHXH & BHYT", "Bảo hiểm xã hội, bảo hiểm y tế và chức năng liên quan.", null, listOf("bhyt_lookup", "bhyt_initial_facility", "social_insurance_history")),
        AppProfile("etax", "eTax Mobile", "Thuế & doanh nghiệp", "Thuế điện tử và các chức năng được hỗ trợ chính thức.", null, listOf("tax_close", "tax_status_03", "tax_obligation"))
    )

    val functions: List<FunctionNode> = listOf(
        fn("open_vneid", "Định danh & giấy tờ", "VNeID", "Mở ứng dụng", "Mở VNeID", "Mở ứng dụng VNeID đã cài trên thiết bị.", listOf("vneid", "cccd", "định danh điện tử", "giấy tờ số"), AnswerMode.ACTION_ONLY,
            routes = listOf(RouteSpec("open_vneid_pkg", RouteType.PACKAGE, "com.vnid", "Mở VNeID", 80, VerificationStatus.VERIFIED, "com.vnid"))),
        fn("passport_service", "Định danh & giấy tờ", "Hộ chiếu", "Thủ tục", "Hộ chiếu", "Tìm thủ tục hoặc kênh chính thức liên quan đến hộ chiếu.", listOf("hộ chiếu", "làm passport", "cấp hộ chiếu", "đổi hộ chiếu"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_public_procedure_local"), status = DataStatus.UNKNOWN),
        fn("residence_service", "Định danh & giấy tờ", "Cư trú", "Thủ tục", "Cư trú", "Tìm thủ tục cư trú phù hợp theo nhu cầu.", listOf("cư trú", "tạm trú", "thường trú", "xác nhận cư trú"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_public_procedure_local"), status = DataStatus.UNKNOWN),
        fn("public_procedure", "Dịch vụ công", "Thủ tục hành chính", "Tra cứu", "Tra cứu thủ tục hành chính", "Tìm đúng thủ tục, hồ sơ và kênh thực hiện từ thư viện cục bộ.", listOf("thủ tục hành chính", "dịch vụ công", "làm thủ tục", "hồ sơ cần gì"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_public_procedure_local"), status = DataStatus.UNKNOWN),
        fn("application_status", "Dịch vụ công", "Hồ sơ", "Tra cứu", "Tra cứu tình trạng hồ sơ", "Xác định kênh phù hợp để kiểm tra trạng thái hồ sơ.", listOf("tình trạng hồ sơ", "hồ sơ đến đâu", "tra cứu hồ sơ", "kết quả hồ sơ"), AnswerMode.ANSWER_AND_ACTION),
        fn("tax_close", "Thuế & doanh nghiệp", "Mã số thuế", "Thủ tục", "Chấm dứt hiệu lực mã số thuế", "Xác định loại chủ thể và trạng thái trước khi dẫn đến đúng thủ tục.", listOf("đóng mã số thuế", "chấm dứt mã số thuế", "đóng mst", "chấm dứt hiệu lực mã số thuế"), AnswerMode.ANSWER_AND_ACTION, required = setOf("tax_subject")),
        fn("tax_status_03", "Thuế & doanh nghiệp", "Mã số thuế", "Trạng thái doanh nghiệp", "Xử lý trạng thái thuế 03", "Giải thích trạng thái và dẫn tiếp theo mã lý do khi dữ liệu local đã được xác minh.", listOf("trạng thái 03", "mã số thuế 03", "doanh nghiệp trạng thái 03"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_tax_status_local"), status = DataStatus.UNKNOWN),
        fn("tax_obligation", "Thuế & doanh nghiệp", "Nghĩa vụ thuế", "Tra cứu", "Nghĩa vụ thuế", "Tìm kênh phù hợp để kiểm tra nghĩa vụ thuế.", listOf("nghĩa vụ thuế", "nợ thuế", "thuế phải nộp", "kiểm tra thuế"), AnswerMode.ANSWER_AND_ACTION),
        fn("business_status", "Thuế & doanh nghiệp", "Doanh nghiệp", "Tra cứu", "Trạng thái doanh nghiệp", "Đối chiếu trạng thái doanh nghiệp theo dữ liệu đã nạp.", listOf("trạng thái doanh nghiệp", "doanh nghiệp đang hoạt động", "doanh nghiệp ngừng hoạt động"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_tax_status_local"), status = DataStatus.UNKNOWN),
        fn("bhyt_lookup", "BHXH & BHYT", "BHYT", "Tra cứu", "Tra cứu BHYT", "Tra cứu BHYT qua kênh chính thức đã được cấu hình và xác minh.", listOf("bhyt", "bảo hiểm y tế", "thẻ bhyt", "hạn thẻ bhyt", "tra cứu bhyt"), AnswerMode.ANSWER_AND_ACTION),
        fn("bhyt_initial_facility", "BHXH & BHYT", "BHYT", "Đăng ký KCB ban đầu", "Cơ sở đăng ký KCB BHYT ban đầu", "Đối chiếu cơ sở với danh sách KCB BHYT ban đầu hiện hành trong thư viện local.", listOf("đăng ký bhyt", "kcb ban đầu", "khám chữa bệnh ban đầu", "bệnh viện có đăng ký bhyt", "chợ rẫy bhyt"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_bhyt_initial_local"), status = DataStatus.UNKNOWN),
        fn("social_insurance_history", "BHXH & BHYT", "BHXH", "Tra cứu", "Quá trình tham gia BHXH", "Tìm kênh phù hợp để xem quá trình tham gia BHXH.", listOf("quá trình bhxh", "đóng bhxh", "thời gian đóng bảo hiểm", "bảo hiểm xã hội"), AnswerMode.ANSWER_AND_ACTION),
        fn("health_facility", "Y tế", "Cơ sở y tế", "Tìm dịch vụ", "Tìm cơ sở y tế", "Tìm cơ sở y tế theo chuyên khoa và khu vực từ dữ liệu local.", listOf("bệnh viện", "phòng khám", "cơ sở y tế", "khám ở đâu"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_health_facility_local"), status = DataStatus.UNKNOWN),
        fn("eye_hospital", "Y tế", "Cơ sở y tế", "Tìm dịch vụ", "Tìm bệnh viện chuyên khoa Mắt", "Tìm cơ sở y tế phù hợp theo chuyên khoa và khu vực từ dữ liệu local.", listOf("bệnh viện mắt", "bệnh viện chuyên về mắt", "nhãn khoa", "khám mắt"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_health_facility_local"), status = DataStatus.UNKNOWN),
        fn("emergency_care", "Y tế", "Cấp cứu", "Tìm dịch vụ", "Tìm cơ sở cấp cứu", "Tìm cơ sở cấp cứu phù hợp theo khu vực đã có trong dữ liệu local.", listOf("cấp cứu", "bệnh viện cấp cứu", "cấp cứu gần"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_health_facility_local"), status = DataStatus.UNKNOWN),
        fn("traffic_fine", "Giao thông", "Vi phạm giao thông", "Phạt nguội", "Xử lý phạt nguội", "Tra cứu lỗi, nơi xử lý hoặc kênh nộp phạt theo nhu cầu cụ thể.", listOf("phạt nguội", "tôi bị phạt nguội", "nộp phạt", "vi phạm giao thông"), AnswerMode.NEED_MORE_INFO),
        fn("vehicle_lookup", "Giao thông", "Phương tiện", "Tra cứu", "Tra cứu phương tiện", "Tìm kênh chính thức phù hợp cho nhu cầu về phương tiện.", listOf("phương tiện", "xe của tôi", "thông tin xe", "đăng ký xe"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_transport_local"), status = DataStatus.UNKNOWN),
        fn("vehicle_inspection", "Giao thông", "Đăng kiểm", "Tra cứu", "Đăng kiểm phương tiện", "Tìm thông tin hoặc kênh thực hiện liên quan đăng kiểm.", listOf("đăng kiểm", "hạn đăng kiểm", "trung tâm đăng kiểm"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_transport_local"), status = DataStatus.UNKNOWN),
        fn("etc_topup", "Giao thông", "ETC", "Nạp tiền", "Nạp tiền tài khoản ETC", "Tìm app/kênh đã xác minh có thể nạp tài khoản ETC.", listOf("nạp etc", "nạp tiền thu phí", "tài khoản thu phí", "vetc", "epass"), AnswerMode.ANSWER_AND_ACTION),
        fn("electricity_payment", "Điện", "Thanh toán dịch vụ", "Thanh toán", "Đóng tiền điện", "Nhận diện đơn vị và tìm kênh thanh toán đã xác minh.", listOf("đóng tiền điện", "thanh toán tiền điện", "hóa đơn điện", "tiền điện"), AnswerMode.ANSWER_AND_ACTION, required = setOf("customer_or_provider")),
        fn("power_outage", "Điện", "Cung cấp điện", "Tra cứu", "Lịch ngừng cấp điện", "Tra lịch ngừng cấp điện theo khu vực từ dữ liệu local.", listOf("lịch cắt điện", "mất điện", "ngừng cấp điện", "lịch mất điện"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_utility_provider_local"), status = DataStatus.UNKNOWN),
        fn("water_payment", "Nước", "Thanh toán dịch vụ", "Thanh toán", "Đóng tiền nước", "Nhận diện đơn vị cấp nước từ dữ liệu local; nếu chưa đủ sẽ hỏi Tỉnh/Thành hoặc đơn vị.", listOf("đóng tiền nước", "thanh toán tiền nước", "hóa đơn nước", "tiền nước"), AnswerMode.ANSWER_AND_ACTION, required = setOf("customer_or_provider")),
        fn("water_outage", "Nước", "Cung cấp nước", "Tra cứu", "Lịch ngừng cấp nước", "Tra lịch ngừng cấp nước theo khu vực từ dữ liệu local.", listOf("cúp nước", "mất nước", "ngừng cấp nước", "lịch cúp nước"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_utility_provider_local"), status = DataStatus.UNKNOWN),
        fn("mobile_topup", "Viễn thông & Internet", "Di động", "Nạp tiền", "Nạp tiền điện thoại", "Xác định số nhận và số tiền rồi tìm kênh đã xác minh trên thiết bị.", listOf("nạp tiền điện thoại", "nạp điện thoại", "nạp 4g", "nạp 5g", "mua data"), AnswerMode.ANSWER_AND_ACTION),
        fn("internet_bill", "Viễn thông & Internet", "Internet", "Thanh toán", "Thanh toán Internet", "Tìm nhà cung cấp và kênh thanh toán phù hợp.", listOf("đóng tiền internet", "cước internet", "wifi", "thanh toán mạng"), AnswerMode.ANSWER_AND_ACTION),
        fn("telecom_package", "Viễn thông & Internet", "Di động", "Tra cứu", "Gói cước di động", "Tìm chức năng phù hợp để kiểm tra hoặc đăng ký gói cước.", listOf("gói cước", "data", "4g", "5g", "gói internet điện thoại"), AnswerMode.ANSWER_AND_ACTION),
        fn("bill_payment_channel", "Ngân hàng & thanh toán", "Thanh toán", "Tìm kênh", "Tìm ứng dụng thanh toán", "Đối chiếu Local Capability Registry để tìm ứng dụng có thể thanh toán dịch vụ.", listOf("app nào thanh toán", "ứng dụng nào thanh toán", "ngân hàng nào thanh toán", "ví nào thanh toán"), AnswerMode.ANSWER_ONLY),
        fn("bank_transfer", "Ngân hàng & thanh toán", "Ngân hàng", "Gọi chức năng", "Chuyển tiền", "Tìm app ngân hàng đã được người dùng thêm hoặc xác minh để mở chức năng phù hợp.", listOf("chuyển tiền", "mở ngân hàng", "chuyển khoản"), AnswerMode.ACTION_ONLY),
        fn("tuition_payment", "Giáo dục", "Học phí", "Thanh toán", "Đóng học phí", "Tìm trường/đơn vị và kênh thanh toán phù hợp.", listOf("đóng học phí", "nộp học phí", "học phí"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_education_local"), status = DataStatus.UNKNOWN),
        fn("admission_info", "Giáo dục", "Tuyển sinh", "Tra cứu", "Thông tin tuyển sinh", "Tra thông tin tuyển sinh từ dữ liệu local đã nạp.", listOf("tuyển sinh", "đăng ký xét tuyển", "nhập học", "hồ sơ nhập học"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_education_local"), status = DataStatus.UNKNOWN),
        fn("unemployment_benefit", "Việc làm & lao động", "Bảo hiểm thất nghiệp", "Thủ tục", "Trợ cấp thất nghiệp", "Tìm điều kiện, hồ sơ và nơi thực hiện từ dữ liệu local.", listOf("trợ cấp thất nghiệp", "bảo hiểm thất nghiệp", "thất nghiệp"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_labor_local"), status = DataStatus.UNKNOWN),
        fn("job_service", "Việc làm & lao động", "Việc làm", "Tìm dịch vụ", "Dịch vụ việc làm", "Tìm trung tâm hoặc thủ tục việc làm phù hợp theo dữ liệu local.", listOf("trung tâm việc làm", "tìm việc", "dịch vụ việc làm"), AnswerMode.ANSWER_ONLY, sourceIds = listOf("src_labor_local"), status = DataStatus.UNKNOWN),
        fn("land_procedure", "Nhà đất & xây dựng", "Đất đai", "Thủ tục", "Thủ tục đất đai", "Tìm thủ tục đất đai và cơ quan xử lý phù hợp.", listOf("đất đai", "sổ đỏ", "giấy chứng nhận quyền sử dụng đất", "thủ tục nhà đất"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_land_local"), status = DataStatus.UNKNOWN),
        fn("planning_lookup", "Nhà đất & xây dựng", "Quy hoạch", "Tra cứu", "Tra cứu quy hoạch", "Tìm nguồn tra cứu quy hoạch chính thức đã được cấu hình.", listOf("quy hoạch", "tra quy hoạch", "quy hoạch đất"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_land_local"), status = DataStatus.UNKNOWN),
        fn("construction_permit", "Nhà đất & xây dựng", "Xây dựng", "Thủ tục", "Giấy phép xây dựng", "Tìm thủ tục và kênh thực hiện giấy phép xây dựng.", listOf("giấy phép xây dựng", "xin phép xây dựng", "xây nhà cần gì"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_land_local"), status = DataStatus.UNKNOWN),
        fn("birth_registration", "Tư pháp & hộ tịch", "Hộ tịch", "Thủ tục", "Đăng ký khai sinh", "Tìm hồ sơ và kênh thực hiện đăng ký khai sinh.", listOf("khai sinh", "đăng ký khai sinh", "làm giấy khai sinh"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_civil_local"), status = DataStatus.UNKNOWN),
        fn("marriage_registration", "Tư pháp & hộ tịch", "Hộ tịch", "Thủ tục", "Đăng ký kết hôn", "Tìm hồ sơ và kênh thực hiện đăng ký kết hôn.", listOf("đăng ký kết hôn", "kết hôn", "làm giấy kết hôn"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_civil_local"), status = DataStatus.UNKNOWN),
        fn("criminal_record", "Tư pháp & hộ tịch", "Tư pháp", "Thủ tục", "Lý lịch tư pháp", "Tìm thủ tục cấp Phiếu lý lịch tư pháp phù hợp.", listOf("lý lịch tư pháp", "phiếu lý lịch tư pháp"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_civil_local"), status = DataStatus.UNKNOWN),
        fn("social_support", "An sinh xã hội", "Trợ cấp", "Tra cứu", "Trợ cấp và bảo trợ xã hội", "Tìm nhóm trợ cấp, điều kiện và nơi thực hiện từ dữ liệu local.", listOf("trợ cấp", "bảo trợ xã hội", "người có công", "hỗ trợ xã hội"), AnswerMode.ANSWER_AND_ACTION, sourceIds = listOf("src_labor_local"), status = DataStatus.UNKNOWN),
        fn("citizen_feedback", "Công dân số địa phương", "Phản ánh", "Gọi chức năng", "Phản ánh hiện trường", "Tìm app/cổng địa phương có chức năng phản ánh đã được cấu hình.", listOf("phản ánh hiện trường", "phản ánh đô thị", "góp ý chính quyền"), AnswerMode.ACTION_ONLY),
        fn("local_public_service", "Công dân số địa phương", "Dịch vụ địa phương", "Tra cứu", "Dịch vụ công địa phương", "Tìm chức năng địa phương phù hợp trong Registry.", listOf("công dân số", "dịch vụ địa phương", "dịch vụ đô thị"), AnswerMode.ANSWER_AND_ACTION),
        fn("party_member_notebook", "Công việc Đảng", "Sổ tay Đảng viên", "Gọi chức năng", "Sổ tay Đảng viên", "Tìm ứng dụng/chức năng đã được người dùng cấu hình và xác minh.", listOf("sổ tay đảng viên", "đảng viên", "sinh hoạt đảng"), AnswerMode.ACTION_ONLY),
        fn("party_fee", "Công việc Đảng", "Đảng phí", "Thanh toán", "Đóng Đảng phí", "Tìm đúng ứng dụng hoặc kênh đã được cấu hình để thực hiện.", listOf("đóng đảng phí", "đảng phí", "nộp đảng phí"), AnswerMode.ACTION_ONLY),
        fn("urban_environment", "Môi trường & đô thị", "Môi trường", "Tra cứu", "Thông tin môi trường đô thị", "Tìm nguồn dữ liệu địa phương đã nạp về môi trường và đô thị.", listOf("môi trường", "rác thải", "ô nhiễm", "chất lượng không khí"), AnswerMode.ANSWER_ONLY),
        fn("community_service", "Văn hóa & cộng đồng", "Cộng đồng", "Tìm dịch vụ", "Dịch vụ văn hóa và cộng đồng", "Tìm dịch vụ văn hóa, thư viện, nhà văn hóa hoặc tiện ích cộng đồng từ dữ liệu local.", listOf("nhà văn hóa", "thư viện", "văn hóa", "cộng đồng"), AnswerMode.ANSWER_ONLY)
    )

    private fun fn(id:String,field:String,service:String,group:String,title:String,description:String,keywords:List<String>,answerMode:AnswerMode,routes:List<RouteSpec> = emptyList(),sourceIds:List<String> = emptyList(),required:Set<String> = emptySet(),status:DataStatus = DataStatus.CURRENT) = FunctionNode(id,field,service,group,title,description,keywords,answerMode,routes,sourceIds,required,status)
    fun sourceById(id:String): SourceRef? = sources.firstOrNull { it.id == id }
    fun sourcesFor(function:FunctionNode): List<SourceRef> = function.sourceIds.mapNotNull(::sourceById)
}
